package builder

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"
)

// ExportLua renders the whole document as a runnable Kalipso-style Lua script:
// a header, function main(), and one block per form. Used for JSON documents
// (no source to preserve), missing files, and tests. For .lua workspaces the
// server prefers RebuildLua (rebuild.go), which splices changed forms into the
// original source instead of regenerating the file wholesale.
func ExportLua(d *Document) string {
	var sb strings.Builder
	title := "kalua-form"
	if f := firstForm(d); f != nil {
		title = f.Name
	}
	fmt.Fprintf(&sb, "-- %s — generated by KALUA Form Builder\n", title)
	fmt.Fprintf(&sb, "-- Generated %s\n\n", time.Now().Format("2006-01-02 15:04:05"))

	sb.WriteString("function main()\n")
	for _, f := range d.Forms {
		exportFormLua(&sb, f, "  ", true)
	}
	sb.WriteString("end\n")
	return sb.String()
}

// GenerateFormLua renders a single form block (k.form.new … controls …
// handlers + stubs … k.form.show) indented by p, WITHOUT the main() wrapper.
// Used by the source-preserving splice (rebuild.go) and by whole-file export.
// emitShow=false keeps a form without a literal k.form.show free of a
// generated show (its dynamic show line stays in the source).
func GenerateFormLua(f *Form, p string, emitShow bool) string {
	var sb strings.Builder
	exportFormLua(&sb, f, p, emitShow)
	return sb.String()
}

func exportFormLua(sb *strings.Builder, f *Form, p string, emitShow bool) {
	if f == nil {
		return
	}
	exportFormNew(sb, f, p)
	for _, c := range f.Controls {
		exportControl(sb, f, c, p)
	}
	// Imported / hand-written handlers are re-emitted VERBATIM (exact source
	// text captured by Import) so saving never rewrites, reformats, or demotes
	// an existing k.form.on. Entries without a captured body belong to
	// non-owned (preserved-in-place) statements and are skipped — the original
	// line already sits in the file.
	exportHandlers(sb, f)
	exportDefaultHandlers(sb, f, p)
	if emitShow {
		fmt.Fprintf(sb, "%sk.form.show(%q)\n", p, f.Name)
	}
}

// exportHandlers emits the captured k.form.on statements: form-level
// (@form) handlers first, then each control's handlers in control order, then
// orphaned handlers kept verbatim for renamed (stale) controls.
func exportHandlers(sb *strings.Builder, f *Form) {
	for _, ev := range f.Handlers["@form"] {
		if ev == "" {
			continue
		}
		if b := f.HandlerBodies["@form."+ev]; b != "" {
			sb.WriteString(b + "\n")
		}
	}
	for _, c := range f.Controls {
		if c == nil {
			continue
		}
		for _, ev := range f.Handlers[c.Name] {
			if ev == "" {
				continue
			}
			if b := f.HandlerBodies[c.Name+"."+ev]; b != "" {
				sb.WriteString(b + "\n")
			}
		}
	}
	if len(f.OrphanKeys) > 0 {
		keys := f.OrphanKeys
		sort.Strings(keys)
		for _, name := range keys {
			for _, ev := range f.Handlers[name] {
				if ev == "" {
					continue
				}
				if b := f.HandlerBodies[name+"."+ev]; b != "" {
					sb.WriteString(b + "\n")
				}
			}
		}
	}
}

// hasCtrl reports whether the form has a control with the given name.
func hasCtrl(f *Form, name string) bool {
	for _, c := range f.Controls {
		if c != nil && c.Name == name {
			return true
		}
	}
	return false
}

// defaultFormEvents are the form-level lifecycle events stubbed for every
// generated app. High-frequency events (on_idle, key_pressed) are deliberately
// excluded so the trace output stays readable.
var defaultFormEvents = []string{"open_form", "after_open_form", "close_form"}

// defaultEventsForControl lists the events a builder-created control should be
// wired to, using the wire event names the runtime dispatches on (e.g. "click"
// for buttons, not the inline-opt alias "onclick").
func defaultEventsForControl(c *Control) []string {
	switch c.Type {
	case "image":
		if c.Opts["clickable"] == true {
			return []string{"click"}
		}
		return nil
	case "looper":
		return []string{"onselect", "onclick"}
	case "chart":
		return []string{"chart_click", "chart_legend_click"}
	case "button":
		return []string{"click"}
	case "textbox", "combo", "list", "checkbox", "radio", "table":
		return []string{"selection_change"}
	}
	return nil
}

// exportDefaultHandlers emits auto-generated k.form.on stubs for the form and
// each control, skipping any (form|ctrl, event) that already has a handler.
func exportDefaultHandlers(sb *strings.Builder, f *Form, p string) {
	for _, ev := range defaultFormEvents {
		if !hasHandler(f, "@form", ev, nil) {
			printHandlerStub(sb, p, f.Name, "@form", ev)
		}
	}
	for _, c := range f.Controls {
		for _, ev := range defaultEventsForControl(c) {
			if hasHandler(f, c.Name, ev, c) {
				continue
			}
			printHandlerStub(sb, p, f.Name, c.Name, ev)
		}
	}
}

// hasHandler reports whether (form|ctrl, event) already has a handler: an
// imported k.form.on registration, a captured body, or an inline onclick opt
// (which the runtime registers as the "click" handler — a generated stub would
// otherwise clobber it).
func hasHandler(f *Form, ctrlName, event string, c *Control) bool {
	if evs := f.Handlers[ctrlName]; evs != nil && contains(evs, event) {
		return true
	}
	return c != nil && event == "click" && c.Inline["onclick"] != ""
}

// printHandlerStub emits k.form.on with a body that prints the event path, so
// running an exported app traces every wired event to the host log.
func printHandlerStub(sb *strings.Builder, p, formName, ctrlName, event string) {
	if ctrlName == "@form" {
		fmt.Fprintf(sb, "%sk.form.on(%q, %q, function()\n", p, formName, event)
		fmt.Fprintf(sb, "%s  k.print(%s)\n", p, luaQuote(formName+"."+event))
		fmt.Fprintf(sb, "%send)\n\n", p)
		return
	}
	fmt.Fprintf(sb, "%sk.form.on(%q, %q, %q, function()\n", p, formName, ctrlName, event)
	fmt.Fprintf(sb, "%s  k.print(%s)\n", p, luaQuote(formName+"."+ctrlName+"."+event))
	fmt.Fprintf(sb, "%send)\n\n", p)
}

func exportFormNew(sb *strings.Builder, f *Form, p string) {
	var opts []string
	if f.Title != "" {
		opts = append(opts, fmt.Sprintf("title=%s", luaQuote(f.Title)))
	}
	layout := f.Layout
	if layout == "" {
		layout = "vertical"
	}
	opts = append(opts, fmt.Sprintf("layout=%q", layout))
	align := f.Align
	if align == "" {
		align = "left"
	}
	opts = append(opts, fmt.Sprintf("align=%q", align))
	if f.Gap != nil {
		opts = append(opts, fmt.Sprintf("gap=%d", *f.Gap))
	}
	if len(f.Cells) > 0 {
		opts = append(opts, "cells="+exportCells(f.Cells))
	}
	fmt.Fprintf(sb, "%sk.form.new(%q, {%s})\n\n", p, f.Name, strings.Join(opts, ", "))
}

func exportCells(cells []*CellDef) string {
	var parts []string
	for _, c := range cells {
		if c == nil || c.Id == "" {
			continue
		}
		var f []string
		f = append(f, fmt.Sprintf("id=%q", c.Id))
		if c.Width > 0 {
			f = append(f, fmt.Sprintf("width=%d", c.Width))
		}
		if c.Bg != "" {
			f = append(f, fmt.Sprintf("bg=%q", c.Bg))
		}
		if c.Align != "" {
			f = append(f, fmt.Sprintf("align=%q", c.Align))
		}
		if c.Border != nil {
			var b []string
			if c.Border.Width > 0 {
				b = append(b, fmt.Sprintf("width=%d", c.Border.Width))
			}
			if c.Border.Color != "" {
				b = append(b, fmt.Sprintf("color=%q", c.Border.Color))
			}
			f = append(f, "border={"+strings.Join(b, ", ")+"}")
		}
		parts = append(parts, "{"+strings.Join(f, ", ")+"}")
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func exportControl(sb *strings.Builder, f *Form, c *Control, p string) {
	// Deterministic key order: JSON opts first, then import-preserved inline
	// function options (e.g. onclick) so handlers are re-injected on Save.
	keys := sortedKeys(c.Opts)
	var opts []string
	hasDB := false
	for _, k := range keys {
		v := c.Opts[k]
		if k == "db" {
			hasDB = true
			continue // DB handles are runtime values; cannot be exported
		}
		if v == nil {
			continue
		}
		if k == "items" {
			opts = append(opts, "items = "+itemsLuaLiteral(v))
			continue
		}
		opts = append(opts, fmt.Sprintf("%s = %s", k, jsonToLuaLiteral(v)))
	}
	for _, k := range sortedKeysStr(c.Inline) {
		opts = append(opts, fmt.Sprintf("%s = %s", k, c.Inline[k]))
	}
	if c.Type == "table" || c.Type == "looper" {
		hasDB = true
	}
	if hasDB {
		fmt.Fprintf(sb, "%s-- k.ctrl.%s(%q, %q, {...}) configured with a DB handle (assigned at runtime)\n",
			p, c.Type, f.Name, c.Name)
	}
	if len(opts) > 3 || len(c.Inline) > 0 {
		fmt.Fprintf(sb, "%sk.ctrl.%s(%q, %q, {\n", p, c.Type, f.Name, c.Name)
		for _, o := range opts {
			fmt.Fprintf(sb, "%s  %s,\n", p, o)
		}
		fmt.Fprintf(sb, "%s})\n\n", p)
	} else {
		fmt.Fprintf(sb, "%sk.ctrl.%s(%q, %q, {%s})\n\n", p, c.Type, f.Name, c.Name, strings.Join(opts, ", "))
	}
}

func jsonToLuaLiteral(v any) string {
	switch t := v.(type) {
	case nil:
		return "nil"
	case string:
		return luaQuote(t)
	case float64:
		return formatNumber(t)
	case bool:
		return strconv.FormatBool(t)
	case []any:
		parts := make([]string, 0, len(t))
		for _, item := range t {
			parts = append(parts, jsonToLuaLiteral(item))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	case map[string]any:
		keys := sortedKeys(t)
		parts := make([]string, 0, len(keys))
		for _, k := range keys {
			parts = append(parts, fmt.Sprintf("%s = %s", luaKey(k), jsonToLuaLiteral(t[k])))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	default:
		return "nil"
	}
}

// luaKey renders a Lua table key: bare identifier when possible, else the
// ["key"] form (quoted string keys directly are a syntax error).
func luaKey(k string) string {
	if identRe.MatchString(k) {
		return k
	}
	return "[" + luaQuote(k) + "]"
}

// itemsLuaLiteral renders the ordered JSON items representation
// ([{key,display},...]) as the runtime map literal {key = "display"}.
func itemsLuaLiteral(v any) string {
	arr, ok := v.([]any)
	if !ok {
		return "{}"
	}
	parts := make([]string, 0, len(arr))
	for _, item := range arr {
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		key, _ := m["key"].(string)
		display, _ := m["display"].(string)
		if display == "" {
			display = key
		}
		parts = append(parts, fmt.Sprintf("%s = %s", luaKey(key), luaQuote(display)))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}
func formatNumber(n float64) string {
	if n == float64(int64(n)) {
		return strconv.FormatInt(int64(n), 10)
	}
	return strconv.FormatFloat(n, 'f', -1, 64)
}

func luaQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedKeysStr(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}