package builder

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"
)

// ExportLua renders the document's form as a runnable Kalipso-style Lua script
// (the same shape KALUA applications use, and the lossless inverse of Import).
func ExportLua(d *Document) string {
	var sb strings.Builder
	f := d.Form

	fmt.Fprintf(&sb, "-- %s — generated by KALUA Form Builder\n", f.Name)
	fmt.Fprintf(&sb, "-- Generated %s\n\n", time.Now().Format("2006-01-02 15:04:05"))

	sb.WriteString("function main()\n")
	exportFormNew(&sb, f)

	for _, c := range f.Controls {
		exportControl(&sb, f.Name, c)
	}

	// Emit handler scaffolds for controls that hold form.on registrations.
	for _, c := range f.Controls {
		events := f.Handlers[c.Name]
		if len(events) == 0 {
			continue
		}
		for _, ev := range events {
			fmt.Fprintf(&sb, "  k.form.on(%q, %q, %q, function()\n", f.Name, c.Name, ev)
			fmt.Fprintf(&sb, "    -- TODO: handle '%s' on '%s'\n", ev, c.Name)
			fmt.Fprintf(&sb, "  end)\n\n")
		}
	}

	fmt.Fprintf(&sb, "  k.form.show(%q)\n", f.Name)
	sb.WriteString("end\n")

	return sb.String()
}

func exportFormNew(sb *strings.Builder, f *Form) {
	var opts []string
	if f.Title != "" {
		opts = append(opts, fmt.Sprintf("title=%s", luaQuote(f.Title)))
	}
	layout := f.Layout
	if layout == "" {
		layout = "vertical"
	}
	opts = append(opts, fmt.Sprintf("layout=%q", layout))
	align := f.Align
	if align == "" {
		align = "left"
	}
	opts = append(opts, fmt.Sprintf("align=%q", align))
	if f.Gap != nil {
		opts = append(opts, fmt.Sprintf("gap=%d", *f.Gap))
	}
	if len(f.Cells) > 0 {
		opts = append(opts, "cells="+exportCells(f.Cells))
	}
	fmt.Fprintf(sb, "  k.form.new(%q, {%s})\n\n", f.Name, strings.Join(opts, ", "))
}

func exportCells(cells []*CellDef) string {
	var parts []string
	for _, c := range cells {
		if c == nil || c.Id == "" {
			continue
		}
		var f []string
		f = append(f, fmt.Sprintf("id=%q", c.Id))
		if c.Width > 0 {
			f = append(f, fmt.Sprintf("width=%d", c.Width))
		}
		if c.Bg != "" {
			f = append(f, fmt.Sprintf("bg=%q", c.Bg))
		}
		if c.Align != "" {
			f = append(f, fmt.Sprintf("align=%q", c.Align))
		}
		if c.Border != nil {
			var b []string
			if c.Border.Width > 0 {
				b = append(b, fmt.Sprintf("width=%d", c.Border.Width))
			}
			if c.Border.Color != "" {
				b = append(b, fmt.Sprintf("color=%q", c.Border.Color))
			}
			f = append(f, "border={"+strings.Join(b, ", ")+"}")
		}
		parts = append(parts, "{"+strings.Join(f, ", ")+"}")
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func exportControl(sb *strings.Builder, formName string, c *Control) {
	keys := sortedKeys(c.Opts)
	var opts []string
	hasDB := false
	for _, k := range keys {
		v := c.Opts[k]
		if k == "db" {
			hasDB = true
			continue // DB handles are runtime values; cannot be exported
		}
		if v == nil {
			continue
		}
		if k == "items" {
			opts = append(opts, "items = "+itemsLuaLiteral(v))
			continue
		}
		opts = append(opts, fmt.Sprintf("%s = %s", k, jsonToLuaLiteral(v)))
	}
	if c.Type == "table" || c.Type == "looper" {
		hasDB = true
	}
	if hasDB {
		fmt.Fprintf(sb, "  -- k.ctrl.%s(%q, %q, {...}) configured with a DB handle (assigned at runtime)\n",
			c.Type, formName, c.Name)
	}
	if len(opts) > 3 {
		fmt.Fprintf(sb, "  k.ctrl.%s(%q, %q, {\n", c.Type, formName, c.Name)
		for _, o := range opts {
			fmt.Fprintf(sb, "    %s,\n", o)
		}
		sb.WriteString("  })\n\n")
	} else {
		fmt.Fprintf(sb, "  k.ctrl.%s(%q, %q, {%s})\n\n", c.Type, formName, c.Name, strings.Join(opts, ", "))
	}
}

func jsonToLuaLiteral(v any) string {
	switch t := v.(type) {
	case nil:
		return "nil"
	case string:
		return luaQuote(t)
	case float64:
		return formatNumber(t)
	case bool:
		return strconv.FormatBool(t)
	case []any:
		parts := make([]string, 0, len(t))
		for _, item := range t {
			parts = append(parts, jsonToLuaLiteral(item))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	case map[string]any:
		keys := sortedKeys(t)
		parts := make([]string, 0, len(keys))
		for _, k := range keys {
			parts = append(parts, fmt.Sprintf("%s = %s", luaKey(k), jsonToLuaLiteral(t[k])))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	default:
		return "nil"
	}
}

// luaKey renders a Lua table key: bare identifier when possible, else the
// ["key"] form (quoted string keys directly are a syntax error).
func luaKey(k string) string {
	if identRe.MatchString(k) {
		return k
	}
	return "[" + luaQuote(k) + "]"
}

// itemsLuaLiteral renders the ordered JSON items representation
// ([{key,display},...]) as the runtime map literal {key = "display"}.
func itemsLuaLiteral(v any) string {
	arr, ok := v.([]any)
	if !ok {
		return "{}"
	}
	parts := make([]string, 0, len(arr))
	for _, item := range arr {
		m, ok := item.(map[string]any)
		if !ok {
			continue
		}
		key, _ := m["key"].(string)
		display, _ := m["display"].(string)
		if display == "" {
			display = key
		}
		parts = append(parts, fmt.Sprintf("%s = %s", luaKey(key), luaQuote(display)))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}
func formatNumber(n float64) string {
	if n == float64(int64(n)) {
		return strconv.FormatInt(int64(n), 10)
	}
	return strconv.FormatFloat(n, 'f', -1, 64)
}

func luaQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
